[2021-06-15 19:14:16,619] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_de_prueba.prueba_python 2021-05-20T11:00:00+00:00 [queued]>
[2021-06-15 19:14:16,668] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dag_de_prueba.prueba_python 2021-05-20T11:00:00+00:00 [queued]>
[2021-06-15 19:14:16,670] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 19:14:16,671] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-15 19:14:16,672] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-15 19:14:16,705] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_python> on 2021-05-20T11:00:00+00:00
[2021-06-15 19:14:16,711] {standard_task_runner.py:53} INFO - Started process 2209 to run task
[2021-06-15 19:14:16,918] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dag_de_prueba.prueba_python 2021-05-20T11:00:00+00:00 [running]> 651693a3c8b0
[2021-06-15 19:14:16,992] {logging_mixin.py:112} INFO - hello
[2021-06-15 19:14:16,994] {logging_mixin.py:112} INFO - world
[2021-06-15 19:14:16,997] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-06-15 19:14:17,043] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=dag_de_prueba, task_id=prueba_python, execution_date=20210520T110000, start_date=20210615T191416, end_date=20210615T191417
[2021-06-15 19:14:26,589] {logging_mixin.py:112} INFO - [2021-06-15 19:14:26,588] {local_task_job.py:103} INFO - Task exited with return code 0
