[2021-06-22 19:15:40,508] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagPrueba_xcom.prueba_pull 2021-06-22T19:15:00.249274+00:00 [queued]>
[2021-06-22 19:15:40,564] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: dagPrueba_xcom.prueba_pull 2021-06-22T19:15:00.249274+00:00 [queued]>
[2021-06-22 19:15:40,566] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 19:15:40,569] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-06-22 19:15:40,571] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-06-22 19:15:40,598] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): prueba_pull> on 2021-06-22T19:15:00.249274+00:00
[2021-06-22 19:15:40,610] {standard_task_runner.py:53} INFO - Started process 994 to run task
[2021-06-22 19:15:41,008] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: dagPrueba_xcom.prueba_pull 2021-06-22T19:15:00.249274+00:00 [running]> 651693a3c8b0
[2021-06-22 19:15:41,373] {taskinstance.py:1145} ERROR - 'return_value'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_hello_xcom.py", line 23, in prueba_pull
    ti = context['return_value']
KeyError: 'return_value'
[2021-06-22 19:15:41,409] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=dagPrueba_xcom, task_id=prueba_pull, execution_date=20210622T191500, start_date=20210622T191540, end_date=20210622T191541
[2021-06-22 19:15:50,456] {logging_mixin.py:112} INFO - [2021-06-22 19:15:50,456] {local_task_job.py:103} INFO - Task exited with return code 1
